version: '3.8'

services:
  wishlis-api:
    build:
      context: .
      dockerfile: ./Wishlis.Api/Dockerfile
    environment:
      - 'ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}'
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
      - 'AWS_REGION=${AWS_REGION}'
    ports:
      - "${API_PORT}:8080"
    networks:
      - wishlis-network
  
  wishlis-webapp:
    build:
      context: ./wishlis-webapp
      dockerfile: Dockerfile
    ports:
      - "${WEBAPP_PORT}:80"
    container_name: wishlis_webapp
    networks:
      - wishlis-network
        
networks:
  wishlis-network: