version: '3.8'

services:
  wishlis-api:
    build:
      context: .
      dockerfile: ./Wishlis.Api/Dockerfile
    ports:
      - "8989:8080"
    networks:
      - wishlis-network
  
  wishlis-webapp:
    build:
      context: ./wishlis-webapp
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: wishlis_webapp
    networks:
      - wishlis-network
        
networks:
  wishlis-network: