@Wishlis.Api_HostAddress = http://localhost:5121

@AccessToken = 

GET {{Wishlis.Api_HostAddress}}/v1/users/1
Accept: application/json
Authorization: Bearer {{AccessToken}}
###

DELETE {{Wishlis.Api_HostAddress}}/v1/users?id=1
Accept: application/json
Authorization: Bearer {{AccessToken}}
###

